### ISSUE TITLE
Sahi for 8k images

### ISSUE THREAD

**Issue by wjassim** [obss/sahi#106]
Hi, thank you for providing this great tool. 

I have tested sahi for 8k images but it seemed that the obtained predictions were not that accurate. In some cases, I get two different objects share the same bbox. Also, sometimes I get one object with two bounding boxes. I have tried different values for slices size and overlapping ratio but couldn't improve the results. Using the same object detection model without sahi gives better results.

Is there something that can be done on tuning or setting the parameters of sahi especially on the slice merging part to get more accurate predictions for high resolution images? Thank you

**Comment by fcakyon** [comment]
@wjassim  thanks for your interest, there are some slicing related parameters that can be tuned but atm that may be hard coded (and need to be changed in source).

Can you provide a sample image (if not private) so that we can replicate the issue? Is that a satellite imagery? If I can recreate the issue I can try to adjust the parameters for that case.

**Comment by wjassim** [comment]
Sorry for the late reply. Actually I used the same pic given in your demo (sahi/demo/demo_data/small-vehicles1.jpeg). I first upsampled it to 8k then run sahi on it to see how the tilling and stitching go for it. I tried with other high resolution pics and it seemed to have the same issues.

**Comment by fcakyon** [comment]
You should not upsample an image to see the effect of tiling because object will also get larger in that case. The images should have high resolution in their nature, like wide-area survelliance or satellite imagery tasks. You can directly use the image as in [demo notebook](https://github.com/obss/sahi/blob/main/demo/inference_for_yolov5.ipynb) to see the effect of sliced inference.

**Comment by fcakyon** [comment]
We will extend the demo with more examples (drone surveillance/drone detection/satellite imagery) in the near future :)

**Comment by wjassim** [comment]
Thank you for your reply and note. Ok, I'll check it with real large images. Looking forward to seeing the new demos. Best regards.

**Comment by fcakyon** [comment]
You can check this blog for small object detection from large satellite images using SAHI: https://blog.ml6.eu/how-to-detect-small-objects-in-very-large-images-70234bab0f98
