### ISSUE TITLE
Any plans for batched inference of sliced images?

### ISSUE THREAD

**Issue by AtGrover** [obss/sahi#182]

**Comment by fcakyon** [comment]
@AtGrover yes it is in to-do list but currently but there is no ETA.

We are always open for PRs :)

**Comment by AtGrover** [comment]
Will probably try giving it a shot in the coming days

**Comment by 1skol1** [comment]
Hey @fcakyon ,
I am new to open source contributions, so can you please guide me, I would like to make a PR for this enhancement.

**Comment by fcakyon** [comment]
@AtGrover @1skol1 main issue with batch support is that the order of the slices should be preserved while performing batch inference so that the results of the slices can be merged properly after getting all predictions of a frame.

here is the batch created: https://github.com/obss/sahi/blob/5d7526a1ac0b4c3da13c52a3e6f1da57add93ea3/sahi/predict.py#L210

currently, it inputs only the first image in a batch: https://github.com/obss/sahi/blob/5d7526a1ac0b4c3da13c52a3e6f1da57add93ea3/sahi/predict.py#L215

it should be updated in a way that predictions coming from different batches should be combined after getting the predictions: https://github.com/obss/sahi/blob/5d7526a1ac0b4c3da13c52a3e6f1da57add93ea3/sahi/predict.py#L214

**Comment by 1skol1** [comment]
@fcakyon thanks for the explanation, will give it a try.

**Comment by Fetulhak** [comment]
@fcakyon it will also be great if Sahi tool includes batch inference and COCO evaluation metrics at inference time such as mAP, Recall, and Precision values for the batch.

**Comment by fcakyon** [comment]
@Fetulhak you can use `coco_evaluation.py` script after running `predict.py` script to evaluate classwise and overall mAP Recall Precision: https://github.com/obss/sahi/blob/main/docs/SCRIPTS.md#coco_evaluationpy-script-usage.

**Comment by Fetulhak** [comment]
@fcakyon  Thank you very much. I will check that.
